CREATE DATABASE Better

USE Better

CREATE TABLE Users(
    Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
    Email NVARCHAR(100) NOT NULL,
    Username NVARCHAR(100) NOT NULL,
    FullName NVARCHAR(100),
    Role NVARCHAR(15) NOT NULL,
    Password NVARCHAR(200) NOT NULL,
    Salt NVARCHAR(200) NOT NULL,
    Coins DECIMAL NOT NULL,
    CreatedAt DATETIME NOT NULL
)

CREATE TABLE Matches(
    Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
    Team1 NVARCHAR(100) NOT NULL,
    Team2 NVARCHAR(100) NOT NULL,
    StartTime DATETIME NOT NULL,
    Winner NVARCHAR(100)
)

CREATE TABLE Bets(
    Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
    UserId UNIQUEIDENTIFIER NOT NULL,
    MatchId UNIQUEIDENTIFIER NOT NULL,
    Team NVARCHAR(100) NOT NULL,
    Coins DECIMAL NOT NULL,
)
Drop TABLE Matches;

SELECT * FROM Users;
SELECT * FROM Matches;
SELECT * FROM Bets;